language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli
script: grunt deploy
deploy:
  provider: s3
  access_key_id: "AKIAJ5RMM3264VMARJQQ"
  secret_access_key:
    secure: "S+NEZ9yJpSh4p2v/Hw1Nm5bWKAy99tLNPiiIWBmFG1hWOxKRAfMN+K2oNkB2o4vQ36yNMiBM2Lp5XPG8kWBWvxoza0rQ2Sf3FMylDxRYC1OAIH4jedRQefuGr727LU6UXojjSRcLZ3PbkDDqZztnZboHEVlKVQR1ea5UgoZBP9E=" 
  bucket: docs.particle.io
  skip_cleanup: true
  local-dir: build
  on:
    repo: spark/docs
    branch: master
